### ISSUE TITLE
Issue on Documentation

### ISSUE THREAD

**Issue by naveen521kk** [leifgehrmann/pangocairocffi#9] opened 2020-09-30 10:56 UTC
Why is the API reference blank with only titles?
![image](https://user-images.githubusercontent.com/49693820/94676832-90a9d300-0339-11eb-9465-30e0a16ae491.png)

**Comment by leifgehrmann** [comment] 2020-09-30 11:21
Looks like Sphinx has gone through 2 major releases since I last did a push to master... I can confirm it works in v1.8.5 of Sphinx, so it's definitely that... 

The latest version of Sphinx now generates errors like this:

```
WARNING: autodoc: failed to import function 'create_context' from module 'pangocairocffi'; the following exception was raised:
No module named 'pangocffi'
WARNING: autodoc: failed to import function 'update_context' from module 'pangocairocffi'; the following exception was raised:
No module named 'pangocffi'
WARNING: autodoc: failed to import function 'create_layout' from module 'pangocairocffi'; the following exception was raised:
No module named 'pangocffi'
etc...
```

I'll see if I can fix this soon!

In the meantime, here is a PDF export of the documentation that I've made:

[Python API reference — pangocairocffi 0.3.0 documentation.pdf](https://github.com/leifgehrmann/pangocairocffi/files/5305040/Python.API.reference.pangocairocffi.0.3.0.documentation.pdf)

**Comment by naveen521kk** [comment] 2020-09-30 12:20
Possibly install `pangocffi` would fix it. Just create a requirements.txt in the docs folder and add `pangocffi`.

**Comment by naveen521kk** [comment] 2020-10-07 17:58
Looks like it is fixed.

**Comment by leifgehrmann** [comment] 2020-10-07 18:25
Yep. I used a hacky work around by adding `pangocffi --no-binary :all:` to `docs/requirements.txt` in https://github.com/leifgehrmann/pangocairocffi/pull/10/files#diff-93bd81aa3a2f0c02728220a6b46fb58d

Evidently `pangocffi` on it's own is not enough.

Will close this issue, but discussion on the underlying issue will continue in #8.

**Closed as completed by leifgehrmann** 2020-10-07 18:25 UTC
